/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiSketchConceptRouteImport } from './routes/api/sketch-concept'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as PassTokenRouteImport } from './routes/pass.$token'
import { Route as ProjectsFreshInkRouteImport } from './routes/projects.fresh-ink'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'
import { Route as ApiPublicAgentKeysRouteImport } from './routes/api/public/agent-keys'
import { Route as ApiPublicAvailabilityRouteImport } from './routes/api/public/availability'
import { Route as ApiPublicCapabilitiesRouteImport } from './routes/api/public/capabilities'
import { Route as ApiPublicEventsRouteImport } from './routes/api/public/events'
import { Route as ApiPublicHoldsRouteImport } from './routes/api/public/holds'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicOpenapiDotjsonRouteImport } from './routes/api/public/openapi[.]json'
import { Route as ApiPublicStudioRouteImport } from './routes/api/public/studio'
import { Route as ApiPublicWebhooksRouteImport } from './routes/api/public/webhooks'
import { Route as PassTokenConfirmRouteImport } from './routes/pass_.$token.confirm'
import { Route as ApiPublicBookingsIdRouteImport } from './routes/api/public/bookings.$id'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSketchConceptRoute = ApiSketchConceptRouteImport.update({
  id: '/api/sketch-concept',
  path: '/api/sketch-concept',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PassTokenRoute = PassTokenRouteImport.update({
  id: '/pass/$token',
  path: '/pass/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsFreshInkRoute = ProjectsFreshInkRouteImport.update({
  id: '/fresh-ink',
  path: '/fresh-ink',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentKeysRoute = ApiPublicAgentKeysRouteImport.update({
  id: '/api/public/agent-keys',
  path: '/api/public/agent-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvailabilityRoute = ApiPublicAvailabilityRouteImport.update({
  id: '/api/public/availability',
  path: '/api/public/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCapabilitiesRoute = ApiPublicCapabilitiesRouteImport.update({
  id: '/api/public/capabilities',
  path: '/api/public/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsRoute = ApiPublicEventsRouteImport.update({
  id: '/api/public/events',
  path: '/api/public/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHoldsRoute = ApiPublicHoldsRouteImport.update({
  id: '/api/public/holds',
  path: '/api/public/holds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenapiDotjsonRoute = ApiPublicOpenapiDotjsonRouteImport.update({
  id: '/api/public/openapi.json',
  path: '/api/public/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStudioRoute = ApiPublicStudioRouteImport.update({
  id: '/api/public/studio',
  path: '/api/public/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRoute = ApiPublicWebhooksRouteImport.update({
  id: '/api/public/webhooks',
  path: '/api/public/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const PassTokenConfirmRoute = PassTokenConfirmRouteImport.update({
  id: '/pass_/$token/confirm',
  path: '/pass/$token/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsIdRoute = ApiPublicBookingsIdRouteImport.update({
  id: '/api/public/bookings/$id',
  path: '/api/public/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/licenses': typeof LicensesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/sketch-concept': typeof ApiSketchConceptRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/pass/$token': typeof PassTokenRoute
  '/projects/fresh-ink': typeof ProjectsFreshInkRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/agent-keys': typeof ApiPublicAgentKeysRoute
  '/api/public/availability': typeof ApiPublicAvailabilityRoute
  '/api/public/capabilities': typeof ApiPublicCapabilitiesRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/holds': typeof ApiPublicHoldsRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/studio': typeof ApiPublicStudioRoute
  '/api/public/webhooks': typeof ApiPublicWebhooksRoute
  '/pass/$token/confirm': typeof PassTokenConfirmRoute
  '/api/public/bookings/$id': typeof ApiPublicBookingsIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/licenses': typeof LicensesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/sketch-concept': typeof ApiSketchConceptRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/pass/$token': typeof PassTokenRoute
  '/projects/fresh-ink': typeof ProjectsFreshInkRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/agent-keys': typeof ApiPublicAgentKeysRoute
  '/api/public/availability': typeof ApiPublicAvailabilityRoute
  '/api/public/capabilities': typeof ApiPublicCapabilitiesRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/holds': typeof ApiPublicHoldsRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/studio': typeof ApiPublicStudioRoute
  '/api/public/webhooks': typeof ApiPublicWebhooksRoute
  '/pass/$token/confirm': typeof PassTokenConfirmRoute
  '/api/public/bookings/$id': typeof ApiPublicBookingsIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/licenses': typeof LicensesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/sketch-concept': typeof ApiSketchConceptRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/pass/$token': typeof PassTokenRoute
  '/projects/fresh-ink': typeof ProjectsFreshInkRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/agent-keys': typeof ApiPublicAgentKeysRoute
  '/api/public/availability': typeof ApiPublicAvailabilityRoute
  '/api/public/capabilities': typeof ApiPublicCapabilitiesRoute
  '/api/public/events': typeof ApiPublicEventsRoute
  '/api/public/holds': typeof ApiPublicHoldsRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/studio': typeof ApiPublicStudioRoute
  '/api/public/webhooks': typeof ApiPublicWebhooksRoute
  '/pass_/$token/confirm': typeof PassTokenConfirmRoute
  '/api/public/bookings/$id': typeof ApiPublicBookingsIdRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/contact'
    | '/developers'
    | '/licenses'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/sitemap.xml'
    | '/admin'
    | '/api/sketch-concept'
    | '/checkout/$id'
    | '/pass/$token'
    | '/projects/fresh-ink'
    | '/api/public/$'
    | '/api/public/agent-keys'
    | '/api/public/availability'
    | '/api/public/capabilities'
    | '/api/public/events'
    | '/api/public/holds'
    | '/api/public/mcp'
    | '/api/public/openapi.json'
    | '/api/public/studio'
    | '/api/public/webhooks'
    | '/pass/$token/confirm'
    | '/api/public/bookings/$id'
    | '/api/public/hooks/send-reminders'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/auth'
    | '/contact'
    | '/developers'
    | '/licenses'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/sitemap.xml'
    | '/admin'
    | '/api/sketch-concept'
    | '/checkout/$id'
    | '/pass/$token'
    | '/projects/fresh-ink'
    | '/api/public/$'
    | '/api/public/agent-keys'
    | '/api/public/availability'
    | '/api/public/capabilities'
    | '/api/public/events'
    | '/api/public/holds'
    | '/api/public/mcp'
    | '/api/public/openapi.json'
    | '/api/public/studio'
    | '/api/public/webhooks'
    | '/pass/$token/confirm'
    | '/api/public/bookings/$id'
    | '/api/public/hooks/send-reminders'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/agents'
    | '/auth'
    | '/contact'
    | '/developers'
    | '/licenses'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/api/sketch-concept'
    | '/checkout/$id'
    | '/pass/$token'
    | '/projects/fresh-ink'
    | '/api/public/$'
    | '/api/public/agent-keys'
    | '/api/public/availability'
    | '/api/public/capabilities'
    | '/api/public/events'
    | '/api/public/holds'
    | '/api/public/mcp'
    | '/api/public/openapi.json'
    | '/api/public/studio'
    | '/api/public/webhooks'
    | '/pass_/$token/confirm'
    | '/api/public/bookings/$id'
    | '/api/public/hooks/send-reminders'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  LicensesRoute: typeof LicensesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSketchConceptRoute: typeof ApiSketchConceptRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  PassTokenRoute: typeof PassTokenRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
  ApiPublicAgentKeysRoute: typeof ApiPublicAgentKeysRoute
  ApiPublicAvailabilityRoute: typeof ApiPublicAvailabilityRoute
  ApiPublicCapabilitiesRoute: typeof ApiPublicCapabilitiesRoute
  ApiPublicEventsRoute: typeof ApiPublicEventsRoute
  ApiPublicHoldsRoute: typeof ApiPublicHoldsRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicOpenapiDotjsonRoute: typeof ApiPublicOpenapiDotjsonRoute
  ApiPublicStudioRoute: typeof ApiPublicStudioRoute
  ApiPublicWebhooksRoute: typeof ApiPublicWebhooksRoute
  PassTokenConfirmRoute: typeof PassTokenConfirmRoute
  ApiPublicBookingsIdRoute: typeof ApiPublicBookingsIdRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/sketch-concept': {
      id: '/api/sketch-concept'
      path: '/api/sketch-concept'
      fullPath: '/api/sketch-concept'
      preLoaderRoute: typeof ApiSketchConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass/$token': {
      id: '/pass/$token'
      path: '/pass/$token'
      fullPath: '/pass/$token'
      preLoaderRoute: typeof PassTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/fresh-ink': {
      id: '/projects/fresh-ink'
      path: '/fresh-ink'
      fullPath: '/projects/fresh-ink'
      preLoaderRoute: typeof ProjectsFreshInkRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-keys': {
      id: '/api/public/agent-keys'
      path: '/api/public/agent-keys'
      fullPath: '/api/public/agent-keys'
      preLoaderRoute: typeof ApiPublicAgentKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/availability': {
      id: '/api/public/availability'
      path: '/api/public/availability'
      fullPath: '/api/public/availability'
      preLoaderRoute: typeof ApiPublicAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/capabilities': {
      id: '/api/public/capabilities'
      path: '/api/public/capabilities'
      fullPath: '/api/public/capabilities'
      preLoaderRoute: typeof ApiPublicCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events': {
      id: '/api/public/events'
      path: '/api/public/events'
      fullPath: '/api/public/events'
      preLoaderRoute: typeof ApiPublicEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/holds': {
      id: '/api/public/holds'
      path: '/api/public/holds'
      fullPath: '/api/public/holds'
      preLoaderRoute: typeof ApiPublicHoldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openapi.json': {
      id: '/api/public/openapi.json'
      path: '/api/public/openapi.json'
      fullPath: '/api/public/openapi.json'
      preLoaderRoute: typeof ApiPublicOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/studio': {
      id: '/api/public/studio'
      path: '/api/public/studio'
      fullPath: '/api/public/studio'
      preLoaderRoute: typeof ApiPublicStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks': {
      id: '/api/public/webhooks'
      path: '/api/public/webhooks'
      fullPath: '/api/public/webhooks'
      preLoaderRoute: typeof ApiPublicWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass_/$token/confirm': {
      id: '/pass_/$token/confirm'
      path: '/pass/$token/confirm'
      fullPath: '/pass/$token/confirm'
      preLoaderRoute: typeof PassTokenConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings/$id': {
      id: '/api/public/bookings/$id'
      path: '/api/public/bookings/$id'
      fullPath: '/api/public/bookings/$id'
      preLoaderRoute: typeof ApiPublicBookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProjectsRouteChildren {
  ProjectsFreshInkRoute: typeof ProjectsFreshInkRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsFreshInkRoute: ProjectsFreshInkRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  LicensesRoute: LicensesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSketchConceptRoute: ApiSketchConceptRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  PassTokenRoute: PassTokenRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
  ApiPublicAgentKeysRoute: ApiPublicAgentKeysRoute,
  ApiPublicAvailabilityRoute: ApiPublicAvailabilityRoute,
  ApiPublicCapabilitiesRoute: ApiPublicCapabilitiesRoute,
  ApiPublicEventsRoute: ApiPublicEventsRoute,
  ApiPublicHoldsRoute: ApiPublicHoldsRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicOpenapiDotjsonRoute: ApiPublicOpenapiDotjsonRoute,
  ApiPublicStudioRoute: ApiPublicStudioRoute,
  ApiPublicWebhooksRoute: ApiPublicWebhooksRoute,
  PassTokenConfirmRoute: PassTokenConfirmRoute,
  ApiPublicBookingsIdRoute: ApiPublicBookingsIdRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
